### ISSUE TITLE
JwtAuthentication.php on line 126

### ISSUE THREAD

**Issue by elvispdosreis** [tuupola/slim-jwt-auth#114]
PHP Parse error:  syntax error, unexpected '|', expecting variable (T_VARIABLE) in /home/xxxxx/vendor/tuupola/slim-jwt-auth/src/JwtAuthentication.php on line 126

**Comment by tuupola** [comment]
What is the code at that specific file and line?

**Comment by tuupola** [comment]
What is the PHP version and what version of the middleware you are using? Minimum requirement for 3.x is PHP 7.1.

**Comment by ketencek** [comment]
Hi Parse error: syntax error, unexpected '|', expecting variable (T_VARIABLE) in /Users/xxx/yyy/vendor/tuupola/slim-jwt-auth/src/JwtAuthentication.php on line 126

my php 7.1.14

my install  details 

container-interop/container-interop 1.2.0  Promoting the interoperability of container objects (DIC, SL, etc.)
doctrine/instantiator               1.1.0  A small, lightweight utility to instantiate objects in PHP without invoking their constructors
firebase/php-jwt                    v5.0.0 A simple library to encode and decode JSON Web Tokens (JWT) in PHP. Should conform to the current spec.
http-interop/http-factory           0.3.0  Common interface for HTTP message factories
monolog/monolog                     1.23.0 Sends your logs to files, sockets, inboxes, databases and various web services
myclabs/deep-copy                   1.7.0  Create deep copies (clones) of your objects
nikic/fast-route                    v1.3.0 Fast request router for PHP
phpdocumentor/reflection-common     1.0.1  Common reflection classes used by phpdocumentor to reflect the code structure
phpdocumentor/reflection-docblock   4.3.0  With this component, a library can provide support for annotations via DocBlocks or otherwise retrieve informati...
phpdocumentor/type-resolver         0.4.0 
phpspec/prophecy                    1.7.6  Highly opinionated mocking framework for PHP 5.3+
phpunit/php-code-coverage           4.0.8  Library that provides collection, processing, and rendering functionality for PHP code coverage information.
phpunit/php-file-iterator           1.4.5  FilterIterator implementation that filters files based on a list of suffixes.
phpunit/php-text-template           1.2.1  Simple template engine.
phpunit/php-timer                   1.0.9  Utility class for timing
phpunit/php-token-stream            2.0.2  Wrapper around PHP's tokenizer extension.
phpunit/phpunit                     5.7.27 The PHP Unit Testing framework.
phpunit/phpunit-mock-objects        3.4.4  Mock Object library for PHPUnit
pimple/pimple                       v3.2.3 Pimple, a simple Dependency Injection Container
psr/container                       1.0.0  Common Container Interface (PHP FIG PSR-11)
psr/http-message                    1.0.1  Common interface for HTTP messages
psr/http-server-handler             1.0.0  Common interface for HTTP server-side request handler
psr/http-server-middleware          1.0.0  Common interface for HTTP server-side middleware
psr/log                             1.0.2  Common interface for logging libraries
sebastian/code-unit-reverse-lookup  1.0.1  Looks up which function or method a line of code belongs to
sebastian/comparator                1.2.4  Provides the functionality to compare PHP values for equality
sebastian/diff                      1.4.3  Diff implementation
sebastian/environment               2.0.0  Provides functionality to handle HHVM/PHP environments
sebastian/exporter                  2.0.0  Provides the functionality to export PHP variables for visualization
sebastian/global-state              1.1.1  Snapshotting of global state
sebastian/object-enumerator         2.0.1  Traverses array structures and object graphs to enumerate all referenced objects
sebastian/recursion-context         2.0.0  Provides functionality to recursively process PHP variables
sebastian/resource-operations       1.0.0  Provides a list of PHP built-in functions that operate on resources
sebastian/version                   2.0.1  Library that helps with managing the version number of Git-hosted PHP projects
slim/middleware                     1.0.0  Slim Framework middleware
slim/php-view                       2.2.0  Render PHP view scripts into a PSR-7 Response object.
slim/slim                           3.10.0 Slim is a PHP micro framework that helps you quickly write simple yet powerful web applications and APIs
symfony/yaml                        v4.0.9 Symfony Yaml Component
tuupola/callable-handler            0.3.0  Compatibility layer for PSR-7 double pass and PSR-15 middlewares.
tuupola/http-factory                0.3.0  Lightweight autodiscovering PSR-17 HTTP factories
tuupola/slim-jwt-auth               3.0.0  PSR-7 and PSR-15 JWT Authentication Middleware
webmozart/assert                    1.3.0  Assertions to validate method input/output with nice error messages.

**Comment by math00** [comment]
Same error here... I'm using PHP 7.1.17 and middleware 3.0

**Comment by tuupola** [comment]
Are you sure the webserver is really running 7.1.17? You get that error if [using 7.0.x](https://travis-ci.org/tuupola/slim-jwt-auth/jobs/380973877) which is not supported.

Put a file called `test.php` into document root with the following contents `<?php phpinfo(); ?>`. Access that with web browser and see what PHP version you are running.

**Comment by elvispdosreis** [comment]
yes it was the problem of the php version I did the upgrade and it worked
