### ISSUE TITLE
Why 400 "Bad Request" if token exists but not decodable?

### ISSUE THREAD

**Issue by vollyimnetz** [tuupola/slim-jwt-auth#16]
Hi,
thanks for the lib. I wounder if there is a specific reason behind returning HTTP-Status 400 when the token can not be decoded?

Background: If i request a resource with a expired token i currently get a 400 (instead of 401). But 400 has, at least for me, the meaning: the request has a bad syntax or can not be processed. I would assume a 401: something wrong with the authentification.

https://github.com/tuupola/slim-jwt-auth/blob/master/src/JwtAuthentication.php#L99
In the code you already checked if a token exists (and throw a 401 if not). After that you throw a 400, if it is noch decodable. Is this common practice?

**Comment by tuupola** [comment]
There was a reason but I do not remember what is was anymore. That said, I now also tend to think response should be 401. See also #12.

**Comment by tuupola** [comment]
It returns `401` now. Will do release soonish.

**Comment by vollyimnetz** [comment]
Thanks a lot.

**Comment by SamanthaAdrichem** [comment]
We needed this fix aswell, because an expired token also gives the 400 bad request error.

However it would be better if you catch the exception types and render a response based on that, for example the ExpiredException should return a 401 unauthorized, yet the malformed, invalid token could return bad request.

This fix solves everything for us though ;) so no need for changes
