### ISSUE TITLE
More complex path and passthrough

### ISSUE THREAD

**Issue by OliverZiegler** [tuupola/slim-jwt-auth#19]
I really like this middleware!

One feature I'm missing is to define more complex PathRules for an REST API.

It would be nice if one can tell the passthrough on which HTTP method it should be possible.

Example:
* I want to be able to passthrough all GET requests except one/two/three.
* I want to passthrough only POST on route "/login" not all

Is there any way to accomplish this currently?

**Comment by ronaldo-systemar** [comment]
+1

**Comment by tuupola** [comment]
*"I want to be able to passthrough all GET requests except one/two/three."*

If this is one GET route called `/one/two/three` use

```php
new \Slim\Middleware\JwtAuthentication\RequestPathRule([
    "path" => "/one/two/three"
])
```

Or if it is three GET routes called `/one` `/two` and /three` then:

```php
new \Slim\Middleware\JwtAuthentication\RequestPathRule([
    "path" => ["/one", "/two", "/three"]
])
```

*"I want to passthrough only POST on route "/login" not all"*

For this you can implement your own rule. It only needs to be a callable. Either implement [RuleInterface](https://github.com/tuupola/slim-jwt-auth/blob/master/src/JwtAuthentication/RuleInterface.php) or use anonymous function. Since it is impossible to cater for everyones needs I intentionally included the possibility to write custom rules.

**Comment by OliverZiegler** [comment]
Thanks a lot for this quick answer!!

The second option was what I searched for!

For my login Route I will try to implement my own RuleInterface. 
But I think an option to define path and methods at the same time would be a nice extension to this.

If I can work it out I will make a pull request accordingly.

**Comment by nicgene** [comment]
In case anybody is looking to implement a rule for something similar.

_"I want to passthrough only POST on route "/login" not all"_

https://gist.github.com/dupkey/27e0b113829b3065a253e19c5f4d7712
