### ISSUE TITLE
Allow Multiple Secrets

### ISSUE THREAD

**Issue by SmoshySmosh** [tuupola/slim-jwt-auth#45]
I can't find this in the documentation, so I was wondering how one would go about accepting multiple JWT Secrets. For example, I would like to generate a new secret for every client who I give access.

```
Client1 => 'client1secret'

Client2 => 'client2secret'
```

Is this possible?

**Comment by tuupola** [comment]
Are you sure you are not mixing `secret` with the token?

**Comment by SmoshySmosh** [comment]
I believe so. I'm new to JWT based authentication so I can't quite articulate this question as well as I would like to.

Basically what I want is to accept public keys from every new client that I can store in a database or something secure server side and they can sign JWTs with their paired private key. This way I can revoke access at any given time to any individual client and not everyone who is using my API.

Does that make more sense?

**Comment by tuupola** [comment]
Ok so plan is to use RS256 instead of HS256 and each user provides their own public key. How would the workflow look? If each user provides their own key then before validating the token you must know which user is sending you the token. How do you know which public key to use for each incoming token?

If you only want to be able to blacklist users and you are going to hit database anyway you could also use HS256. Just store user id in `sub` claim and compare use that value to check if user is blacklisted.

**Comment by SmoshySmosh** [comment]
I believe it would be possible to break apart the JWT Token and look at the iss claim. Using the iss claim you can determine which key the token belongs to and then grab the key and validate to ensure that it's a valid token.

Is there anything wrong with my thinking here?

**Comment by masadelante** [comment]
Actually, that's how the OpenID Connect Discovery works. When receiving a JWT signed with RSA256, a lookup is made to the provider's (issuer's) URI to fetch the provider's different endpoints, and the issuer's public key as well. 

https://openid.net/specs/openid-connect-discovery-1_0.html

**Comment by tuupola** [comment]
Starting with `3.2.0` it is possible to pass in array of secret keys. The middleware then chooses the correct key based on the `kid` claim in the token header. For example:

```php
$middleware = new JwtAuthentication([
    "secret" => [
        "acme" =>"supersecretkeyyoushouldnotcommittogithub",
        "beta" =>"anothersecretkeyfornevertocommittogithub"
    ]
]);
```

Token with this header would use the `supersecretkeyyoushouldnotcommittogithub` as secret key.

```javascript
{
  "typ": "JWT",
  "alg": "HS256",
  "kid": "acme"
}
```

**Comment by hari2m** [comment]
@tuupola is the array of secrets a key-value pair?

**Comment by tuupola** [comment]
Yes. You can see an example in the comment above.

**Comment by gnl1** [comment]
Hi Mika, 

I would like to ask you if the following is feasible using your great middleware!

What I want to achieve is to eliminate the use of short lived tokens and long lasting refresh tokens as well as sending a new token back to the user on each call (as you have suggested in another thread).

The way that I'm thinking of doing it, is that I will use a secret that is constructed by two parts. A common part for all users and a second part that is unique for each user and is stored in a database. When the user logs in then I generate a token based on the common one and the user's specific secret. When a request for a protected route comes in then your middleware gets activated but unfortunately it uses a SINGLE static secret to check the validity of the token and its missing the second part of the secret that was used to sign the token. 

What I would like to be able to do is have your middleware "callback" a function in order to build the proper secret for each user, prior to validating the token. (I don't mind hitting the database to retrieve the "current" second part!)

The new feature you've added recently to support multiple keys and pick one according to the kid claim is great, but unfortunately I don't think that adding 1000 keys or even more (according to the number of users) is logical! 

Do you have an idea on how to go about it, since this flow will help me to have an everlasting token and be able to invalidate tokens just by changing the user's part in the database and thus, be able to force the user to re-login in case that his/hers subscription expired, the token was compromised, etc!!

**Comment by vanjoechua** [comment]
Has anyone tried implementing this with Auth0. I cannot seem to get Auth0 to include a kid in the access token it generates. I don't want to create a new API project just for Auth0 to work against. Hope someone has an idea.

**Comment by Dadinos** [comment]
> Starting with `3.2.0` it is possible to pass in array of secret keys. The middleware then chooses the correct key based on the `kid` claim in the token header. For example:
> 
> ```
> $middleware = new JwtAuthentication([
>     "secret" => [
>         "acme" =>"supersecretkeyyoushouldnotcommittogithub",
>         "beta" =>"anothersecretkeyfornevertocommittogithub"
>     ]
> ]);
> ```
> 
> Token with this header would use the `supersecretkeyyoushouldnotcommittogithub` as secret key.
> 
> ```js
> {
>   "typ": "JWT",
>   "alg": "HS256",
>   "kid": "acme"
> }
> ```

Is it possible when no kid is given we can fall back on a default key?
