### ISSUE TITLE
How to invalidate old JWT Token

### ISSUE THREAD

**Issue by sujit-baniya** [tuupola/slim-jwt-auth#76]
Hello,

First I would like to thank you for such great library. I'm using this library on Slim Framework. I'm successfully able to generate JWT token after login. If I login again, I get another token through which I could access secured API. Here I'm able to access secured API through old JWT token.

How can invalidate old JWT token if  new JWT token is created after login?

**Comment by tuupola** [comment]
JWT does not offer any mechanics other than expiration time for invalidating a token. 

Technically you could save info about the valid tokens, for example `jti` claim or even the whole token to a database table. When user uses JWT you then compare tokens `jti` or the whole token to the info in the database.

Bad thing is now your authentication is now no longer stateless. You have to query database for each request. One of the main points of using JWT or any other [similar authentication scheme](https://github.com/tuupola/branca-spec) is to have stateless authentication.

Instead of worrying of old tokens I usually just set short ttl so they expire reasonably fast.
