### ISSUE TITLE
How to passtrought OPTIONS pre-flight

### ISSUE THREAD

**Issue by jaimecuellar14** [tuupola/slim-jwt-auth#99]
Hello, I am trying to make an  API, and the login worked so far, but when i try to do another request with Authentication Bearer, i get 

    No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 
    'http://localhost:8000' is therefore not allowed access. The response had HTTP status code 500.

Here is how I have the `middleware.php`

    $app->add(new \Slim\Middleware\JwtAuthentication([
    "path" => "/",
    "logger" => $container['logger'],
    "secret" => "123456789helo_secret",
      "rules" => [
        //Si se quiere agregar una ruta que no requiere del token
        //Se debe agregar a la siguiente lista
      new \Slim\Middleware\JwtAuthentication\RequestPathRule([
          "path" => "/",
          "passthrough" => ["/usuarios", "/login","/usuario"]
      ]),
      new \Slim\Middleware\JwtAuthentication\RequestMethodRule([
          "passthrough" => ["OPTIONS"]
      ]),
      ],
      "callback" => function ($request, $response, $arguments) use ($container) {
      $container["jwt"] = $arguments["decoded"];
     },
      "error" => function ($request, $response, $arguments) {
      $data["status"] = "error";
      $data["message"] = $arguments["message"];
      return $response
          ->withHeader("Content-Type", "application/json")
          ->write(json_encode($data, JSON_UNESCAPED_SLASHES | JSON_PRETTY_PRINT));
      }
    ]));

I am trying to call `/informacion` with this code.

    $http({
     method: 'GET',
     url: 'http://myurl/public/informacion/'+$scope.id,
      headers: {
      'Content-Type': "application/x-www-form-urlencoded",
      "Authorization": "Bearer " +$scope.token
      }
      }).then(function (response) {
     console.log(response);
      });

I read somewhere else, that for some methods the browser first send OPTIONS preflight, but the OPTIONS cant have authentication header, looking at my chrome dev tools, my OPTIONS get status of `200 OK` but my GET gets the error mentioned before. I added `/informacion` to `passthrough` and works just fine, but I wanted to be sending the jwt token. Do you have any idea how can I solve this situation.

Thanks.

**Comment by tuupola** [comment]
The error you mention, was it an exception in the code? Maybe related to this https://github.com/tuupola/cors-middleware/issues/2? Basically if there is an exception Slim does not execute the middleware stack.

**Comment by tuupola** [comment]
I would ask this in the support forum of the JavaScript library you are using. GitHub issues are for reporting bugs. But basically as the error message says you should send an `Access-Control-Allow-Origin` header with the response.

**Comment by jaimecuellar14** [comment]
I am... this is code I  have

    $app->options('/{routes:.+}', function ($request, $response, $args) {
    return $response;
     });

     $app->add(function ($req, $res, $next) {
     $response = $next($req, $res);
    return $response
            ->withHeader('Access-Control-Allow-Origin', '*')
            ->withHeader('Access-Control-Allow-Credentials','true')
            ->withHeader('Access-Control-Allow-Headers', 'X-Requested-With, Content-Type, Accept, Origin, 
    Authorization ')
            ->withHeader('Access-Control-Allow-Methods', 'GET, POST, PUT, DELETE,PATCH');
     });

Sorry I tought it was something with the JWT auth or something.

**Comment by PeterBocan** [comment]
@GreyBlade I had similar issue. I have NGINX using as a proxy for FastCGI to PHP-FPM. I have shamelessly forced the rules in NGINX config.Heavily inspired by https://gist.github.com/chrisallenlane/6367574 Hope it will help you.

**Comment by phuze** [comment]
@GreyBlade 

That error ...

> No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 
'http://localhost:8000' is therefore not allowed access. The response had HTTP status code 500.

... is a CORS issue with two possible situations occurring.

First, its important to note that Google Chrome does not support localhost for CORS requests (neither does Firefox I think). This has been a known 'bug' as others have called it and [reported since 2010](https://bugs.chromium.org/p/chromium/issues/detail?id=67743). There are extensions and workarounds, you'll find them in that issue thread.

If your intent on doing things using chrome in a localhost environment, you could try disabling [chromes web security](https://stackoverflow.com/questions/3102819/disable-same-origin-policy-in-chrome).

Secondly, when (if) you deploy this to an internet-facing server environment, then you'll need to ensure you configure your http server accordingly.

I do not use nginx so I can't help there. However, if you use apache2, then you will need to configure your virtual host configuration to include the appropriate headers. If your API is for enterprise (company) purposes, and depending on what it serves, it may not be advisable to use the wildcard (which denotes the entire internet is allowed to make requests to your api server).

```
Header set Access-Control-Allow-Origin "*"
Header set Access-Control-Allow-Methods "POST, GET, DELETE, OPTIONS"
Header set Access-Control-Max-Age "7200"
Header set Access-Control-Allow-Headers "x-requested-with, Content-Type, origin, authorization, accept, client-security-token"
Header set Access-Control-Allow-Credentials "true"
```

Moreover, @GreyBlade @tuupola you should not be returning any of those headers with your response (I'm referring to this bit of code):

```
return $response
        ->withHeader('Access-Control-Allow-Origin', '*')
        ->withHeader('Access-Control-Allow-Credentials','true')
        ->withHeader('Access-Control-Allow-Headers', 'X-Requested-With, Content-Type, Accept, Origin, 
Authorization ')
        ->withHeader('Access-Control-Allow-Methods', 'GET, POST, PUT, DELETE,PATCH');
```

Those headers should be set on the http server that serves your API requests -- passing these headers in your API response will not affect anything.

Your responses should look something like this:

```
return $response
        ->withHeader('Content-Type','application/json')
        ->withStatus(200)
        ->withJson("ok");
```

@PeterBocan Maybe I misunderstand you, but to clarify, modifying your nginx config to set the appropriate headers **is the correct thing to do**.

**Comment by tuupola** [comment]
There is also a [CORS middleware](https://github.com/tuupola/cors-middleware) if editing config files is not possible.

**Comment by jaimecuellar14** [comment]
I had to delete logger part of the code, that was causing the issue
